### ISSUE TITLE
-n / --name option doesn't work correctly

### ISSUE THREAD

**Issue by masukomi** [masukomi/fenestro#11]
when you open multiple files quickly AND pass the `-n <name>`  or `--name <name>` option with each file the initial load will show no content in the main viewing area

<img width="817" alt="cdiff" src="https://cloud.githubusercontent.com/assets/2829/12073162/5f986ef8-b0db-11e5-983f-551fb5a4c03f.png">

AND 

if you click on any of the items you will see the raw HTML code instead of the rendered version

**Comment by masukomi** [comment]
screenshot after clicking one of them:

<img width="817" alt="cdiff" src="https://cloud.githubusercontent.com/assets/2829/12073170/e27c9cb8-b0db-11e5-88af-bb8b6858a744.png">

**Comment by kareman** [comment]
@masukomi Now all files are displayed as HTML. I have not been able to reproduce the problem with no content showing when opening multiple files quickly, it may have been related.
