### ISSUE TITLE
right clicking icon in dock shows documents that don't exist

### ISSUE THREAD

**Issue by masukomi** [masukomi/fenestro#12]
Expected behavior: 
When I right click on the doc i should see a list of the windows that are currently open. I'm not sure what the correct / standard thing to show is when there are no windows currently open.

![screenshot_1_6_16__9_03_am](https://cloud.githubusercontent.com/assets/2829/12144347/0289cdf6-b455-11e5-93fd-ba8d82ec4c4c.png)

**Comment by kareman** [comment]
@masukomi When there are no windows open the list you see there are previously opened files. This doesn't really make much sense for this application, as all files are temporary. I don't know if there is any way to disable this list, but I can look into it if you want.
