### ISSUE TITLE
timeout between new window creation doesn't seem to be being respected

### ISSUE THREAD

**Issue by masukomi** [masukomi/fenestro#18]
I've tried upping the timeout to 20.0 seconds, then throwing a bunch of files at it with varying _sub-second_ delays. i keep getting multiple windows. Each window has multiple items in the sidebar. I can replicate it... but I don't get have a way to replicate it that someone else could do. 

in the example i have locally it loads 2 files in the first window, then loads all the other files in a second window. Another person has tried this and they get many many windows.

**Comment by kareman** [comment]
@masukomi Could you try running `test/test1.bash` and verify it does what it says it should do? This is the script I use to test this functionality. Presumably your scripts try to open a lot more files in one go, roughly how many and are they all local files, from the network or the result of shell commands ?

Also could you check that only one instance of the UI application is opened? During testing I have to make sure there are no other copies of the UI application to prevent them from being opened together with the development version.

And if you run `fenestro -v` it should display `1.0 (6)` both in the terminal and the window which is opened in the UI application. The UI application does not check if the command line application is the newest version, just that it is installed.

**Comment by masukomi** [comment]
it took me quite a while to conclusively prove this. .... what i discovered was that there was an ancient version of Fenestro.app that Xcode had archived and THAT was what was running despite how many times i built or cleaned or ran make. 

So yes. The test for the timeout works correctly. It was user error (kindof).

**Comment by kareman** [comment]
@masukomi 
Yes this is a problem with how the command line app opens files in the gui app, which is by using the launch services of OS X. I could get it to just open the Fenestro app in /Applications, but that will complicate testing, also it would mean users would not be able to install it to other locations. 

Or maybe just have the gui app check that no other versions are already running on launch.

**Comment by masukomi** [comment]
> Yes this is a problem with how the command line app opens files in the gui app, which is by using the launch services of OS X

I disagree. I think it's an issue with XCode / OS X. It doesn't make any sense to randomly make copies of a random build of someone's app. It makes even less sense to prevent those copies from showing up in a Spotlight search. A normal user isn't going to have multiple copies of the app. The few that do will have done so on purpose, and know where those copies are. They won't be surprised be the behavior.

I was surprised because _I_ never made that copy. I never asked for it, and OS X refused to show it to me using normal means.

**Comment by kareman** [comment]
Yes Xcode doesn't always make sense :)

I don't think there is anything we can do to prevent this specific problem, but we could add a "--diagnose"/"--selftest" parameter to  the commandline app which could make it easier to diagnose these kind of problems. Specifically it could check that there is only one Fenestro gui app registered in OS X launch services, and list the locations of all of them if there are several. It could also pass  its build nr to the gui app and have it check that they are of the same version. The report generated by this command, which could be displayed as html in the gui app, could also be useful as an attachment to bug reports from users.
