### ISSUE TITLE
New windows are always aligned with the bottom edge of the screen

### ISSUE THREAD

**Issue by masukomi** [masukomi/fenestro#3]
see attached screenshot. No matter how big the window is when it opens, it is always down in that position.

<img width="1440" alt="fullscreen_11_3_15__8_17_am" src="https://cloud.githubusercontent.com/assets/2829/10908983/a0b6e876-8203-11e5-8cb5-caa7d00bf268.png">

**Comment by kareman** [comment]
What is the desired position? Top left corner?

**Comment by masukomi** [comment]
I checked what Kaleidoscope does, since I use it a lot and have never been unhappy with its placement...

the new window seems centered, and _near_ the top, but not _at_ the top. Let's do something like that.

<img width="1440" alt="fullscreen_11_5_15__7_44_am" src="https://cloud.githubusercontent.com/assets/2829/10968719/249d9110-8391-11e5-8d43-5ab8cf8e8904.png">

**Comment by masukomi** [comment]
This is the weird part for me. The 1st window opens down at the bottom, but subsequent windows are near the top, and each new window offsets itself nicely. 

In the screenshot the 2 window is shifted to the right of the 1 window, and I suspect down a little bit  from where the 1 window would have been normally. just like the 3 window is down and right from 2. If we could just make 1 start where 2 thought 1 was....  that would be fine too.

so instead of 

<img width="1440" alt="fullscreen_11_5_15__7_47_am" src="https://cloud.githubusercontent.com/assets/2829/10968786/aac2f55a-8391-11e5-92c9-b066f249eae8.png">

something like

<img width="742" alt="menubar_and___html_and___html_and___html_and_new_windows_are_always_aligned_with_the_bottom_edge_of_the_screen_ _issue__3_ _masukomi_fenestro_and_1__bash" src="https://cloud.githubusercontent.com/assets/2829/10968846/4aa31ed8-8392-11e5-86e9-c171953ebdeb.png">

I'm betting that's easier than centering, and it'll be better in the long run when someone tries opening a hundred windows. ;)
